#pragma once

#include <vector>
#include <memory>
#include <string>
#include <array>
#include <stack>
#include <queue>
#include <mutex>
#include <thread>
#include <optional>
#include <variant>
#include <functional>
#include <span>
#include <type_traits>
#include <unordered_map>
#include <map>
#include <unordered_set>
#include <list>
#include <fstream>
#include <filesystem>
#include <d3d12.h>
#include <dxgi1_6.h>
#include <windows.h>
#define DML_TARGET_VERSION_USE_LATEST
#include <DirectML.h>
#include <DirectXMath.h>

#include "d3dx12.h"
#include "DirectMLX.h"
#include "D3D12MemAlloc.h"
#include "nfd.h"
#include "entt/entt.hpp"
#include "cereal/archives/binary.hpp"
#include "cereal/types/string.hpp"
#include "cereal/types/vector.hpp"
#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui.h"
#include "Core/Types.h"
#include "Core/Macros.h"
#include "Core/Logging/Log.h"
#include "Graphics/GfxMacros.h"
#include "Math/MathCommon.h"
#include "Utilities/Ref.h"
